# Spatial data analysis: a definition {#sec-spatial-data-analysis-a-definition}

## Interdisciplinarity and perspective

Data analysis and statistics are used in many scientific fields. When the focus is on geographic objects, subjects, their patterns or relationships, we like to talk about **spatial analysis**. However, because geographic data is relevant to many fields and statistical methods are widely used, spatial analysis can be defined and approached differently.

Within geography, we understand the term **spatial analysis** to refer to all quantitative approaches, as opposed to qualitative approaches (although these can also be spatial and analytical). Within the quantitative part of the discipline, however, spatial analysis would mostly refer to **applied statistical approaches**, in contrast to GIS modeling, geosimulation, transportation modeling, or mathematical models. In this sense, **this course is a spatial analysis course**.

However, for those researchers involved in spatial analysis close to regional science and economic geography (and perhaps close to landscape ecology and GIScience), the terms **spatial data analysis or spatial statistics would more strictly refer to the explicit use of geographic information in the modeling process**, not just the consideration of geographic elements. See for example the handbook of Fischer and Getis for discussion and examples.

Similarly, Goodchild and Longley (<https://www.geos.ed.ac.uk/~gisteac/gis_book_abridged/files/ch40.pdf>) suggest more broadly that spatial analysis could simply be a set of methods useful when the data are spatial (i.e. referenced in 2D frame). This definition however as they suggest would be too broad, if it does not address the question of whether the 2D frame actually matters. Rather spatial analysis is

> the subset of analytic techniques whose results will change if the frame changes, or if objects are repositioned within it.

## Links with theory

Science progresses with tools and techniques but also by **testing hypotheses and updating models and theory**. How spatial analysis is linked to theory also depends on fields or sub-fields.

From a quantitative geography viewpoint (adapted from Denise Pumain https://hypergeo.eu/theories-of-spatial-analysis/?lang=en), spatial analysis focuses on **uncovering spatial structures and organizations. These structures can often be generalized into models, such as center-periphery relationships, gravity models, and urban hierarchies and networks**.

The ultimate goal of spatial analysis is then to understand the processes that lead to the formation of these spatial structures.

From a **spatial economic or regional science viewpoint** (as understood by a European quantitative geographer) spatial analysis consists of a set of techniques designed to:

-   Describe the location of activities and how they change over time
-   Estimate **reduced form models**

Unlike **structural form models**, which are direct representations or formulations of theoretical concepts, reduced form models are designed to better align with and fit the data.

There is probably no such a reduced or structural form model in quantitative geography, but in both case anyway, spatial analysis ultimately aims at testing and updating theories.

We very much agree with this perspective here, leading to giving **more importance to the falsification of ideas and the interpretation of estimated coefficients than to prediction** using as many data as possible.

If a variable is used it is because **we have some idea** of its importance and influence on others or its relevance, not just to obtain a fit. Hence we won't use automatic models constructions (no stepwise regression for example) and leave out all the methods (neural networks, random forests, etc.) from which coefficients (if any) are difficult to interpret, even if these methods can be considered to belong to spatial analysis and use geographic data. **This course is not about data mining or data crunching. We use a statistical lens to examine variations across space and how spatial relationships influence socio-economic patterns and behaviors or environmental effects**.
