project:
  type: book

book:
  title: "Introduction to data analysis and R for geographers"
  subtitle: "MAGEO0641 (2024-2025 vintage)"
  author: "Geoffrey Caruso and Léandre Fabri"
  date: "9/10/2024"
  cover-image: cover.png
  favicon: cover.png
  site-url: https://quadtrees.lu/teaching/MAGEO0641
  repo-url: https://github.com/geocaruso/MAGEO0641
  chapters:
    - index.qmd
    - timetable.qmd
    - learning.qmd
    - part: intro.qmd
      chapters:
      - scope.qmd
      - spatial_analysis.qmd
      - space_axiom.qmd
      - space_issues.qmd
    - part: "Getting started with R"
      chapters:
      - getting_started.qmd
      - R_basics.qmd
      - df_functions.qmd
    - part: "Graphics"
      chapters:
      - ggplot.qmd
    - part: "Univariate analysis and distributions"
      chapters:
      - univariate.qmd
      - distributions.qmd
    - part: "Bivariate analysis and regression"
      chapters:
      - correlation.qmd
      - regression.qmd
      - CIregression.qmd
    - part: "Bibliography"
      chapters:
      - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

number-depth: 3
