project:
  type: book

book:
  title: "Introduction to data analysis and R for geographers"
  subtitle: "MAGEO0641 (2024-2025 vintage)"
  author: "Geoffrey Caruso and Léandre Fabri"
  date: "9/10/2024"
  cover-image: images/cover.png
  favicon: images/cover.png
  site-url: https://quadtrees.lu/teaching/MAGEO0641
  repo-url: https://github.com/geocaruso/MAGEO0641
  search: true
  chapters:
    - index.qmd
    - 001_timetable.qmd
    - 002_learning.qmd
    - part: 010_intro.qmd
      chapters:
      - 011_scope.qmd
      - 012_spatial_analysis.qmd
      - 013_space_axiom.qmd
      - 014_space_issues.qmd
    - part: 020_getting_started.qmd
      chapters:
      - 021_Rstudio.qmd
      - 022_vectors.qmd
      - 023_df_lst.qmd
      - 024_df_functions.qmd
      - 025_read_write.qmd
    - part: "Part III - Univariate analysis"
      chapters:
      - 031_sample_population.qmd
      - 032_univariate.qmd
      - 033_discretisation.qmd
      #-Tabulation anc cross-tabulation (apply) 
    - part: "Part IV - Distributions and testing"
      chapters:
      - 041_distributions_unif_normal.qmd
      - 042_CLT_Standardisation.qmd
      - 043_distributions_other_continuous.qmd
    - part: "Part V - Graphics with ggplot"
      chapters:
      - 050_graphics_ggplot.qmd
    - part: "Part VI - Bivariate and regression analysis"
      #chapters:
      #- correlation.qmd
      #- regression.qmd
      #- CIregression.qmd
    - part: "Appendices, Tips, tricks and miscellaneous"
      chapters: 
      - 901_copy_paste.qmd
      - 902_making_data.qmd
      - 903_summarizing.qmd
    - part: "Bibliography"
      chapters:
      - 999_references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

number-depth: 3

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

execute:
  error: true
