# Preface {#sec-preface .unnumbered}

This is the syllabus for the course *Introduction to Data Analysis for Geographers with R* (MAGEO0641) at the Department of Geography and Spatial Planning at the University of Luxembourg. It has been produced as a Quarto book by Geoffrey Caruso and Léandre Fabri with the aim of aggregating and homogenizing different material accumulated over the past few years.

As of today, an overall assemblage is made but additions and fine tuning are still very much needed. We kindly ask students to refer to their notes during class to prepare for the examination and assignments.

The general structure and base material shown here have been organized by Geoffrey Caruso, who originally inherited teaching material from Dominique Peeters. We are grateful to the teaching assistants who were in charge before Léandre Fabri: Mirjam Schindler, Marlène Boura, David Dabin and Jonathan Jones. We remain solely responsible for any mistake or incoherence one would find.

The course is made available online at <https://quadtrees.lu/teaching/MAGEO0641>.

Its associated repository is at: <https://github.com/geocaruso/MAGEO0641> where students will also find the data folder for the examples and exercises.
