# Statistical data analysis for geographers {#sec-statistical-data-analysis-for-geographers}

## Scope {#sec-scope}

This course is an introduction to **standard statistical techniques** that geographers often encounter. Being at the crossroads of different fields, it is necessary for geographers to have a **basic set of tools with which to interact with other experts and modelers** who, although they may use different wording and have their own technical habits, use a common set of concepts and tools to analyze data and test their hypotheses.

In their own work and in their interactions with others, it is also important for geographers to keep in mind that the data they use are quite **specific because they are about located objects or subjects, about places and their interactions.** Most of the time, the data they use is **georeferenced** in some way (accurately or not). This inherently geographic aspect brings with it a number of challenges. In this course, we will highlight these challenges when performing standard data analysis. However, we won't solve any of these geographic problems, and we won't even explicitly use geographic features, i.e., no mapping, no use of georeferencing as such. **Our goal is to equip students with standard statistical methods also used in related fields, with some critical thinking about their geographical nature** or underlying spatial processes. In a nutshell, this is **a journey from elementary statistics to spatial autocorrelation with a standard regression detour**.

## Transparent geographical analysis empowered with R {#sec-transparent-geographical-analysis-empowered-with-r}

The course is a blend of theory and practice, which we believe enhances intuition and understanding. Direct practice also helps - especially for human geographers with little training in quantitative methods - to demystify statistical concepts and provide confidence after repeated applications and interpretations.

Software for statistical analysis has evolved rapidly and R is prominent in many disciplines. It is open and free. It is simply fantastic for spatial data analysis and may well be the only tool geographers really need in their data undertaking, even replacing GIS (Geographic Information Systems) software. You just need to get started with R.

Most of our students have had some sort of theoretical statistics course so far in their studies, so they have probably seen most of the content. Sometimes our students have had some practice with SPSS (or similar) software, but most have not used any real statistical software at all, and have a spreadsheet (e.g., Excel) as their only reference for data management, analysis, and graphing. We chose R for its openness, leadership, large community, and later for its spatial features, but also because it forces students to be transparent and think about every step they take. Data analysis and visualization can be misleading and dangerous, it is necessary to think and facilitate replication for oneself and for others. R, and more generally the use of scripts and command lines, is absolutely necessary to bring robustness and trust.
